name: Quality

on:
  workflow_dispatch:
#  pull_request:
#    branches:
#      - main

## Cancel the previous run if a new one is triggered for the current branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Run Prettier
        run: npx prettier --check './**/*.ts'

      - name: Success
        run: |
          echo "Prettier ran successfully"
          echo "This is a test"
